apiVersion: v2
name: featureflags
description: A Helm chart for Feature Flags Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - feature-flags
  - golang
  - api
maintainers:
  - name: Platform Team
    email: platform@example.com
